AllCops:
  NewCops: enable
  DisplayCopNames: true
  ExtraDetails: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/Send:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/Alias:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
