language: ruby
cache: bundler
rvm:
- 2.2.6
before_script: "./bin/rake db:setup"
script: "./bin/rake"
notifications:
  email: false
addons:
  postgresql: "9.2" # json data type was introduced in postgres 9.2. Travis default is 9.1
