language: ruby
cache: bundler
rvm:
- 2.2.4
before_script: "./bin/rake db:setup"
script: "./bin/rake"
notifications:
  email: false
  slack:
    secure: uDLpvU5cXO1XbuviHlOVWLJF3ZAIvvmFtruUQ5s6yjyDJsMqd1d33LJyaOwttvI8tDkFxuzzkirgDkqSpguGq1wVtmM3q1RjfzbJZq80vFZz9Vx4tj1eWon/+IKmz2c17cHoeMmzBOkrAPBW5qF/RVz7FdomSGo3vI2xlWdBOxfGVTA9uuvkMo+BKR6MCdQvTyRQVamJyQK2ORCzz6QXa7oIQIigSWo7trxt117mythgaC2cK9KgFmkgllnmpz5SUck7FYmGUF7pKEOIQ84dMgAIM3oum+LTu+s5GuLY4nk+NAGFzZ615S7Az4AatUntZVtTaO14jdcY83dFtrCgLYAdrHDcPqFaSMv7gwWbvpAvf3hIkcZGesySEhgymwZxS58ux0z8A+0pxfsIigF+EeZvd2IKivW5XZy9oqVRujgl7cvQ64nampn+L7lUDqniLN0VfjlkJUWzM36VFsh/27xvo6boUaTUCTDu72Iu7DWacJYSNNeyDt2GELtfIj0RY8Ba804y0/8zNTpc504VDuqeZy5glu63C7dtRg7j0Usrr6+DfvcHIN95ZM0T5xydYj+hXcTWQsQ+uWNcNil5ioQYOnYj9Tfk0EJXTG0H9r32gAKMKQJgmcHDnoTbq4FM6nboceHN0u5bsgZC590i0+4QUEm8FnouTJhzdjWLWmI=
addons:
  code_climate:
    repo_token:
      secure: QxWig1BPGKWpKwdHylwi9A/EdsAVkBNRAAXxFTL8K357LWqyq4lS2jUPF3VGn+Vhe3oApQRLZg/qhOCKxOCVOiR5GJaFBtaI3zPDsjmMSd67N2Oh5JIWBiAQ1GanghKIU4P3G+TZI06oZo7MLARRK+Xnbs6FjirFjMPk6r8Fs+dlCg/KEawZpBL+5vT9XPx9VWtSATCE0hg0me5LKCdtJ0CgsxnuAyHz7AP1uRS5sswXPl1Dt1jd2zhj/W3R+qQdqMnVzI2AbDbivfxULuZjQXoEtHfkucYeFGXhiyssNHPVUujFQ10t08F41hEgDJ3qi5DNtTyy+veZP0d/zV5vfoH7MlEA/BTvMtmimwTERibJlKaxfToG8N/jjlNDJwBY3uOtNjoI+bskFas3T5PwmK0cPOfWWxpr2NdWhatTSZ2u7KbhibOeU7mRwYc6y0fqGv2vJHGBYKy0oAKg5l3l36Q1l380VK2+UymEhtUK32vwKFby9n31KWkbBsRUJ9o23LoMsJHCZfI6Hz93zGM0080SZKs79tgMnicfDbsKWS/CS01WQcI+7Aw75F2LcJUaU1IzzvmatxY8QrjgmxAiqlc4Wu++0IZ8bujvmlGwjqhnXLkU/+yvaDnETiT9WQeTSw1LF5WbP1rEla2L4zBNPuaAKsOln1fUgbYV55Qr530=
  postgresql: "9.2" # json data type was introduced in postgres 9.2. Travis default is 9.1
