---
name: Test
on:
  - push
  - pull_request
env:
  DATABASE_TEST_URL: postgres://postgres:postgres@postgres/postgres
  RACK_ENV: test
  REDIS_URL: redis://redis:6379/0
jobs:
  test:
    runs-on: ubuntu-20.04
    container: library/ruby:2.6.7
    services:
      postgres:
        image: library/postgres:9.6
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: library/redis:latest
    steps:
    - run: apt-get update && apt-get install -y postgresql-client
    - uses: actions/checkout@v2
    - run: bundle install
    - run: bin/rake db:setup
    - run: bin/rake db:migrate
    - run: bin/rake
